const Payment = [

    {
        SLNO: 1,
        Order_No: '20351',
        Order_Date:'15/4/2021',
        Rider:'XYZ person',
        Amount_Recieved:'2000',
        Order_Amount:'2000',
        Merchant:'Big Bazar',
        Payment_Mode:'Jazz Cash',
        Ref_No:'IFSC123450',
        Total_Amount:'5000',
        Notification:'XYz Rider paid you 5000rs.',
        Amount_Recieved_Status:'Yes',
        Amount_Paid_Status:'Paid',
        Customer:"uzma",
        Change_Amount:"50rs/-",
        Delivery_Charge:"200rs/-",
        Discount:"30%",
        DeliveryBoy:"RDET",
        Coupon_Code:"12345",
        Date:"15/5/2020",
        Order_Type:"Sinlge",
        Sub_order:"1",
        Order_Amount:"5820",
        Final_Amount:"5894",
        Total_Km:"65",
        Status:"Delivered",
        User:"Arslan",
        Final_Amount:3500,
        Total_Orders:15,
        Payment_By:'Rider',
        Amount_Paid:5000,
        Payment_Date:"15/5/2020",
    },
    {
        SLNO: 2,
        Order_No: '20352',
        Order_Date:'16/4/2021',
        Rider:'XYZ person',
        Amount_Recieved:'1000',
        Order_Amount:'1000',
        Merchant:'Loyal World',
        Payment_Mode:'Card',
        Ref_No:'IFSC123458',
        Total_Amount:'5000',
        Notification:'XYz Rider paid you 1000rs.',
        Amount_Recieved_Status:'No',
       Amount_Paid_Status:'Not Paid',
       Customer:"uzma",
       Change_Amount:"50rs/-",
       Delivery_Charge:"200rs/-",
       Discount:"30%", DeliveryBoy:"RDET",
       Coupon_Code:"12345",
       Date:"15/5/2020",
       Order_Type:"Multiple",
       Sub_order:"4",
        Order_Amount:"5820",
        Final_Amount:"5894",
        Total_Km:"65",
        Status:"Delivered",
        User:"Shabaz",
        Final_Amount:500,
        Total_Orders:9,
        Payment_By:'User',
        Amount_Paid:5500,
        Payment_Date:"15/5/2020",

    },
    {
        SLNO: 3,
        Order_No: '20351',
        Order_Date:'17/4/2021',
        Rider:'XYZ person',
        Amount_Recieved:'5000',
        Order_Amount:'5000',
        Merchant:'Big Bazar',
        Payment_Mode:'Jazz Cash',
        Ref_No:'IFSC123453',
        Total_Amount:'5000',
        Notification:'XYz Rider paid you 2000rs.',
        Amount_Recieved_Status:'Yes',
       Amount_Paid_Status:'Not Paid',
       Customer:"uzma",
       Change_Amount:"50rs/-",
       Delivery_Charge:"200rs/-",
        Discount:"30%", DeliveryBoy:"RDET",
        Coupon_Code:"12345",
       Date:"15/5/2020",
       Order_Type:"Multiple",
       Sub_order:"4",
        Order_Amount:"5820",
        Final_Amount:"5894",
        Total_Km:"65",
        Status:"Delivered",
        User:"Uzma",
        Final_Amount:3500,
        Total_Orders:10,
        Payment_By:'Rider',
        Amount_Paid:8000,
        Payment_Date:"15/5/2020",
    },
]


export default Payment