const usersData = [
    {
        id: 1,
        "SL No":1,
        "Vendors":"NR Vendors",
        "Total Sales":98547,
        "Total Discount":"12695",
        "Grand Total":"987541/-",
        "Date":"12/04/2021",
        "City":"Mysuru",
        "Area":"Saraswathipuram",
       "Order No":"12356",
       "Order value":"1900",
       "Discount":"25",
       "Change Amount":"50",
       "Delivery Charge":"50",
       "Final Amount":"2000",
       "Order Date":"2/5/2021",
       "Order Status":"Completed",
       "Payment Method":"Wallet",
    },
     {
        id: 2,
        "SL No":2,
        "Vendors":"NR Vendors",
        "Total Discount":"9695",
        "Total Sales":124,
        "Grand Total":"987541/-",
        "Date":"10/04/2021",
        "City":"Mysuru",
        "Area":"Saraswathipuram",
        "Order No":"12356",
        "Order value":"1900",
        "Discount":"25",
        "Change Amount":"50",
        "Delivery Charge":"50",
        "Final Amount":"2000",
        "Order Date":"2/5/2021",
        "Order Status":"Completed",
        "Payment Method":"Online",

    },
      {
        id: 3,
        "SL No":3,
        "Vendors":"NR Vendors",
        "Total Discount":"54695",
        "Total Sales":14,
        "Grand Total":"987541/-",
        "Date":"09/04/2021",
        "City":"Mysuru",
        "Area":"Saraswathipuram",
        "Order No":"12356",
        "Order value":"1900",
        "Discount":"25",
        "Change Amount":"50",
        "Delivery Charge":"50",
        "Final Amount":"2000",
        "Order Date":"2/5/2021",
        "Order Status":"Completed",
        "Payment Method":"COD",

    },
      
 
];

export default usersData;