const usersData = [
  {
    "SL No": 1,
    "Vendor Name": "Allen Pharma",
    Mobile: "92-114562315",
    City: "Karachi",
    "E-mail": "kar@gmail.com",
    Sales: "45821/-",
    Feedback: "Nostalgic Service",
    Coupons: "Partnered Vendor",
  },
  {
    "SL No": 2,
    "Vendor Name": "kELEN Laundry",
    Mobile: "92-114562315",
    City: "Karachi",
    "E-mail": "kar@gmail.com",
    Sales: "45821/-",
    FeedBack: "Nostalgic Service",
    Coupons: "Non Partnered Vendor",
  },
  {
    "SL No": 3,
    "Vendor Name": "Data Saloon",
    Mobile: "92-114562315",
    City: "Karachi",
    "E-mail": "kar@gmail.com",
    Sales: "45821/-",
    FeedBack: "Nostalgic Service",
    Coupons: "Partnered Vendor",
  },
  {
    "SL No": 4,
    "Vendor Name": "Allen Pharma",
    Mobile: "92-114562315",
    City: "Karachi",
    "E-mail": "kar@gmail.com",
    Sales: "45821/-",
    FeedBack: "Nostalgic Service",
    Coupons: "Partnered Vendor",
  },
  {
    "SL No": 5,
    "Vendor Name": "Allen Pharma",
    Mobile: "92-114562315",
    City: "Karachi",
    "E-mail": "kar@gmail.com",
    Sales: "45821/-",
    FeedBack: "Nostalgic Service",
    Coupons: "Non Partnered Vendor",
  },
  {
    "SL No": 6,
    "Vendor Name": "Allen Pharma",
    Mobile: "92-114562315",
    City: "Karachi",
    "E-mail": "kar@gmail.com",
    Sales: "45821/-",
    FeedBack: "Nostalgic Service",
    Coupons: "Partnered Vendor",
  },
  {
    "SL No": 7,
    "Vendor Name": "Allen Pharma",
    Mobile: "92-114562315",
    City: "Karachi",
    "E-mail": "kar@gmail.com",
    Sales: "45821/-",
    FeedBack: "Nostalgic Service",
    Coupons: "Non Partnered Vendor",
  },
];

export default usersData;
