const usersData = [
  {
    "SL No": 1,
    "Order No": "11-452",
    Date: "12/04/2021",
    "Item's": "Belt-4 Laundry",
    Quantity: "2-Quan Box",
    Feedback: "Fastest Delivery By Vendor",
    "Total Amount": "2965/-",
    "Total Sales": "54789/-",
    Rider: "Jhon Marphin",
    "Delivery Charges": "315/-",
  },
  {
    "SL No": 2,
    "Order No": "11-452",
    Date: "12/04/2021",
    "Item's": "Belt-4 Saloon",
    Quantity: "1-Quan Box",
    Feedback: "Nostalic Service",
    "Total Amount": "265/-",
    "Total Sales": "--",
    Rider: "Jhon Marphin",
    "Delivery Charges": "315/-",
  },
  {
    "SL No": 3,
    "Order No": "11-452",
    Date: "12/04/2021",
    "Item's": "Pc Software",
    Quantity: "2-Quan Box",
    Feedback: "Nostalic Service",
    "Total Amount": "29650/-",
    "Total Sales": "--",
    Rider: "Jhon Marphin",
    "Delivery Charges": "315/-",
  },
  {
    "SL No": 4,
    "Order No": "11-452",
    Date: "12/04/2021",
    "Item's": "Belt-4 Laundry",
    Quantity: "2-Quan Box",
    Feedback: "Nostalic Service",
    Rider: "Jhon Marphin",
    "Delivery Charges": "315/-",
    "Total Amount": "2965/-",
    "Total Sales": "--",
  },
  {
    "SL No": 5,
    "Order No": "11-452",
    Date: "12/04/2021",
    "Item's": "Belt-4 Laundry",
    Quantity: "2-Quan Box",
    Feedback: "Fastest Delivery By Vendor",
    "Total Amount": "2965/-",
    "Total Sales": "--",
    Rider: "Jhon Marphin",
    "Delivery Charges": "315/-",
  },
  {
    "SL No": 6,
    "Order No": "11-452",
    Date: "12/04/2021",
    "Item's": "Belt-4 Laundry",
    Quantity: "2-Quan Box",
    FeedBack: "Fastest Delivery By Vendor",
    "Total Amount": "2965/-",
    "Total Sales": "--",
    Rider: "Jhon Marphin",
    "Delivery Charges": "315/-",
  },
  {
    "SL No": 7,
    "Order No": "11-452",
    Date: "12/04/2021",
    "Item's": "Belt-4 Laundry",
    Quantity: "2-Quan Box",
    Feedback: "Fastest Delivery By Vendor",
    "Total Amount": "2965/-",
    "Total Sales": "--",
    Rider: "Jhon Marphin",
    "Delivery Charges": "315/-",
  },
];

export default usersData;