
const Riders = [
  {
    id: 1,
    "SLNo": "1",
    Name: "Samppa Nori",
    "E-Mail": "Abcd123@gmail.com",
    Mobile: "9638520147",
    City: "Bangalore",
    "DL No": "KAMN450",
    Date: "15/04/2021",
    "Total Orders": "65",
    "Total Delivery": "60",
    "Non Responded Orders": "5",
    "Total Earnings": "6500",
    Status: "Active",
    "Tips Earned":"500",
    "Joined Date":"21/5/2020",
    "Area":"Saraswathipuram",
    OrderNo:"123654",
    Order_Amount:"1452",
    Customer:"yuos",
    Rider:"tyrt",
    Change_Amount:"1236",
    Customer_Confirmation:"Yes",
    Merchant:"Shabaz",
    Total_Orders:"20",
    Total_Sales:"5000",
    Total_Discounts:"200 rs",
    Total_coupons:"6",
    Service_Charges:"500",
    Rejection_Reason:"Testing Reason",



  },
  {
    id: 2,
    "SLNo": "2",
    Name: "Jhon Doe",
    "E-Mail": "Abcd123@gmail.com",
    Mobile: "9638520147",
    City: "Bangalore",
    "DL No": "JKHN450",
    Date: "15/04/2021",
    "Total Orders": "107",
    Status: "free",
    "Total Orders": "65",
    "Total Delivery": "60",
    "Non Responded Orders": "5",
    "Total Earnings": "6500",
    "Tips Earned":"500",
    "Joined Date":"21/5/2020",
    "Area":"Saraswathipuram",
    OrderNo:"123654",
    Order_Amount:"1452",
    Customer:"yuos",
    Rider:"tyrt",
    Change_Amount:"1236",
    Customer_Confirmation:"Yes",
    Merchant:"Shabaz",
    Total_Orders:"20",
    Total_Sales:"5000",
    Total_Discounts:"200 rs",
    Total_coupons:"6",
    Service_Charges:"500",
    Rejection_Reason:"Testing Reason",
  },
  {
    id: 3,
    "SLNo": "3",
    Name: "Grand Master",
    "E-Mail": "Abcd123@gmail.com",
    Mobile: "9638520147",
    City: "Bangalore",
    "DL No": "87YHG450",
    "Total Orders": "786",
    Status: "Active",
    Date: "15/04/2021",
    "Total Orders": "65",
    "Total Delivery": "60",
    "Non Responded Orders": "5",
    "Total Earnings": "6500",
    "Tips Earned":"500",
    "Joined Date":"21/5/2020",
    "Area":"Saraswathipuram",
    OrderNo:"123654",
    Order_Amount:"1452",
    Customer:"yuos",
    Rider:"tyrt",
    Change_Amount:"1236",
    Customer_Confirmation:"No",
    Merchant:"Shabaz",
    Total_Orders:"20",
    Total_Sales:"5000",
    Total_Discounts:"200 rs",
    Total_coupons:"6",
    Service_Charges:"500",
    Rejection_Reason:"Testing Reason",
    
  },
  {
    id: 4,
    "SLNo": "4",
    Name: "Samppa",
    "E-Mail": "Abcd123@gmail.com",
    Mobile: "9638520147",
    City: "Bangalore",
    "DL No": "HUGFV450",
    "Total Orders": "224",
    Status: "free",
    Date: "15/04/2021",
    "Total Orders": "65",
    "Total Delivery": "60",
    "Non Responded Orders": "5",
    "Total Earnings": "6500",
    "Tips Earned":"500",
    "Joined Date":"21/5/2020",
    "Area":"Saraswathipuram",
    OrderNo:"123654",
    Order_Amount:"1452",
    Customer:"yuos",
    Rider:"tyrt",
    Change_Amount:"1236",
    Customer_Confirmation:"Yes",
    Merchant:"Shabaz",
    Total_Orders:"20",
    Total_Sales:"5000",
    Total_Discounts:"200 rs",
    Total_coupons:"6",
    Service_Charges:"500",
    Rejection_Reason:"Testing Reason",
  },
  {
    id: 5,
    "SLNo": "5",
    Name: "Nori",
    "E-Mail": "Abcd123@gmail.com",
    Mobile: "9638520147",
    City: "Bangalore",
    "DL No": "OOP450",
    "Total Orders": "854",
    Status: "Active",
    Date: "15/04/2021",
    "Total Orders": "65",
    "Total Delivery": "60",
    "Non Responded Orders": "5",
    "Total Earnings": "6500",
    "Tips Earned":"500",
    "Joined Date":"21/5/2020",
    "Area":"Saraswathipuram",
    OrderNo:"123654",
    Order_Amount:"1452",
    Customer:"yuos",
    Rider:"tyrt",
    Change_Amount:"1236",
    Customer_Confirmation:"Yes",
    Merchant:"Shabaz",
    Total_Orders:"20",
    Total_Sales:"5000",
    Total_Discounts:"200 rs",
    Total_coupons:"6",
    Service_Charges:"500",
    Rejection_Reason:"Testing Reason",
  },
  {
    id: 6,
    "SLNo": "6",
    Name: "Kalam",
    "E-Mail": "Abcd123@gmail.com",
    Mobile: "9638520147",
    City: "Bangalore",
    "DL No": "RFETY450",
    "Total Orders": "20",
    Status: "free",
    Date: "15/04/2021",
    "Total Orders": "65",
    "Total Delivery": "60",
    "Non Responded Orders": "5",
    "Total Earnings": "6500",
    "Tips Earned":"500",
    "Joined Date":"21/5/2020",
    "Area":"Saraswathipuram",
    OrderNo:"123654",
    Order_Amount:"1452",
    Customer:"yuos",
    Rider:"tyrt",
    Change_Amount:"1236",
    Customer_Confirmation:"Yes",
    Merchant:"Shabaz",
    Total_Orders:"20",
    Total_Sales:"5000",
    Total_Discounts:"200 rs",
    Total_coupons:"6",
    Service_Charges:"500",
    Rejection_Reason:"Testing Reason",
  },

 
];

export default Riders;